---
title: 'Toronto Gardeners Survey 2018 Analysis: COVID-19'
author: "Shirin Arghandeh"
date: '2020-06-08'
output:
  html_document:
    df_print: paged
---


```{r setup, include=FALSE}
library(readxl)
# Importing and reading survey data.
gardener_data <- read_excel("togardener_survey18.xls", col_names = TRUE)
str(gardener_data)
attach(gardener_data)
```


Cross-tabulation of types of gardens
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)

type_dur_clean <- gardener_data %>%
  dplyr::select(id = `Internal ID`, growing_duration, contains("_garden"))

# Transform so the two variables of interest (garden type and duration) are in two columns. 
# Each person will have 9 rows.
type_dur_long <- type_dur_clean %>%
  pivot_longer(contains("_garden"), names_to = "garden_type", values_to = "indicator") %>%
  replace_na(list(indicator = 0))

# Creating the table
td_cross <- type_dur_long %>%
  group_by(growing_duration, garden_type) %>%
  summarize(num = sum(indicator)) %>%
  pivot_wider(names_from = "garden_type", values_from = "num") %>%
  adorn_totals("row")

```
```{r echo=FALSE}
knitr::kable(td_cross)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
type_plant_clean <- gardener_data %>%
  dplyr::select(id = `Internal ID`, num_plants, contains("_garden"))

type_plant_long <- type_plant_clean %>%
  pivot_longer(contains("_garden"), names_to = "garden_type", values_to = "indicator") %>%
  replace_na(list(indicator = 0))

tp_cross <- type_plant_long %>%
  group_by(num_plants, garden_type) %>%
  summarize(num = sum(indicator)) %>%
  pivot_wider(names_from = "garden_type", values_from = "num") %>%
  adorn_totals("row")

```
```{r echo=FALSE}
knitr::kable(tp_cross)
```

```{r eval=FALSE, include=FALSE}
type_seed_clean <- gardener_data %>%
  dplyr::select(id = `Internal ID`, store_seed, own_seed, frcan_seed, frcoun_seed,
                mecoun_seed, lib_seed, other_seed,
                contains("_garden"))

type_seed_long <- type_seed_clean %>%
  pivot_longer(contains("_garden"), names_to = "garden_type", values_to = "indicator") %>%
  replace_na(list(indicator = 0))

type_seed_long %>%
  group_by(store_seed, own_seed, frcan_seed, frcoun_seed,
                mecoun_seed, lib_seed, other_seed, garden_type) %>%
  summarize(num = sum(indicator)) %>%
  pivot_wider(names_from = "garden_type", values_from = "num")

# "Total" row
type_seed_long %>%
  group_by(garden_type) %>%
  summarize(num = sum(indicator)) %>%
  pivot_wider(names_from = "garden_type", values_from = "num")
```
